# Generated by Django 4.1.2 on 2022-10-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='photo',
            constraint=models.CheckConstraint(check=models.Q(('album_id__gte', 1)), name='negative_album_id'),
        ),
    ]
